swagger: '2.0'
info:
  version: 0.0.1
  title: TodoApi
  description: TodoリストAPI
basePath: /api
paths:
  /todos:
    get:
      description: Todoの全件取得
      parameters:
        - name: filter
          in: query
          description: todo filter by finished
          required: false
          type: string
          enum:
            - open
            - close
            - all
      responses:
        200:
          description: 取得成功
          schema:
            type: array
            items:
              $ref: '#/definitions/Todo'
            example:
              - id: 0
                task: メールチェック
                finish: true
              - id: 1
                task: ミーティング
                finish: false
    post:
      description: 新規Todoの登録
      parameters:
        - name: todo
          in: body
          schema:
            $ref: '#/definitions/Todo'
      responses:
        201:
          description: 登録成功
  /todos/{id}:
    get:
      description: Todo1件の取得
      parameters:
        - name: id
          in: path
          type: number
          required: true
      responses:
        200:
          description: 取得成功
          schema:
            $ref: '#/definitions/Todo'
        404:
          description: リソースが存在しない
    put:
      description: Todo1件の更新
      parameters:
      - name: id
        in: path
        type: number
        required: true
      - name: todo
        in: body
        schema:
          $ref: '#/definitions/Todo'
      responses:
        200:
          description: 更新成功
    delete:
      description: Todo1件の削除
      parameters:
      - name: id
        in: path
        type: number
        required: true
      responses:
        200:
          description: 削除成功
definitions:
  Todo:
    type: object
    properties:
      id:
        type: number
      task:
        type: string
      finish:
        type: boolean
    example:
      id: 0
      task: メールチェック
      finish: true
